# Change these first
owner: scc-mobile # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository

sites:
  - name: ŠCC Mobile - Frontend
    url: https://scc-mobile.thepatik.eu.org
    icon: https://scc-mobile.thepatik.eu.org/cvet_barvni.png
  - name: ŠCC Mobile - Backend
    url: https://scc-mobile-api.thepatik.eu.org
    icon: https://scc-mobile.thepatik.eu.org/cvet_barvni.png
  - name: KER stran
    url: https://ker.sc-celje.si
    icon: https://scc-mobile.thepatik.eu.org/KER_cvet.png
  - name: GL stran
    url: https://gl.sc-celje.si
    icon: https://scc-mobile.thepatik.eu.org/GL_cvet.png
  - name: GVO stran
    url: https://gvo.sc-celje.si
    icon: https://scc-mobile.thepatik.eu.org/GVO_cvet.png  
  - name: SMM stran
    url: https://smm.sc-celje.si
    icon: https://scc-mobile.thepatik.eu.org/SMM_cvet.png  
  - name: SDL stran
    url: https://sdl.sc-celje.si
    icon: https://scc-mobile.thepatik.eu.org/SDL_cvet.png
  - name: Prehrana stran
    url: https://prehrana.sc-celje.si
  - name: EviWeb
    url: https://eportal.sc-celje.si/EWePortal-cgi/EWePortal.exe/getdata?CID=000:-:0000000000&ACT=getPUBCID&PMD=3.079
    icon: https://eportal.sc-celje.si/EWePortal/img/eviwebSIS.ico

status-website:
  baseUrl: /monitor
  logoUrl: https://scc-mobile.thepatik.eu.org/cvet_barvni.png
  name: ŠCC Mobile
  introTitle: "ŠCC Mobile - Neuradna mobilna aplikacija Šolskega centera Celje"
  navbar:
    - title: Status
      href: /
    - title: "ŠCC Mobile"
      href: https://scc-mobile.thepatik.eu.org
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/1 * * * *"
